extraction:
  cpp:
    after_prepare: "pip3 install --user numpy cython 'cmake==3.17'"
    configure:
      command:
      - export PATH="${HOME}/.local/bin:${PATH}"
      - "mkdir build"
      - "cd build && cmake .."
    index:
      build_command: "cd build && make -j2"
  python:
    python_setup:
      requirements:
        - wheel
      requirements_files:
        - requirements.txt
      exclude_requirements:
        - PyOpenGL
        - mayavi
        - pyface
        - pygame
        - traits
        - traitsui
